seanmcne/Microsoft.Xrm.Data.PowerShell

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Added role name support for Add-CrmSecurityRoleToxxx. I also fixed help .examples (just replace some typos, not affected to code).
=> Role Name for Add-CrmSecurityRoleToxx

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
fix functions which has ValueFromPipeline to have begin/process/(end) block appripariately
=> fix functions which has ValueFromPipeline

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
AddedGet-CrmSdkMessageProcessingStepsForPluginAssembly
=> Plug in support

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
just re-order function by name
=> just re-order function by name

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Get-CrmUserSecurityRoles: Added BusinessUnitName as result set
Get-CrmUserPrivilegs: Added PrincipalType, PrincipalName, BusinessUnitName as result set and separate Team's security role privileges.
=> Get crm user privileges enhancement

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> Escape XML for FetchXML

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
fixed query condition to get user rathen than team
=> fixed query condition to get user rathen than team

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
added Set-CrmConnectionCallerId
=> added Set-CrmConnectionCallerId

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
sample usage 
```PowerShell
$results = New-Object System.Collections.Generic.List[PSObject]
$conn = Connect-CrmOnlineDiscovery -InteractiveMode
$fetch = @"
<fetch version="1.0" output-format="xml-platform" mapping="logical" distinct="false" no-lock="true">
<entity name="savedquery">
<attribute name="name" />
<attribute name="fetchxml" />
<attribute name="layoutxml" />
<attribute name="returnedtypecode" />
<order attribute="name" descending="false" />
<filter type="and">
<condition attribute="querytype" operator="eq" value="0" />
<condition attribute="statuscode" operator="eq" value="1" />
</filter>
</entity>
</fetch>
"@
$systemViews = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch -AllRows -WarningAction SilentlyContinue
$current = 1
$total =$systemViews.CrmRecords.Count …
```
=> added Test-CrmViewPerformance

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> Import crm solution

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
- minor string formatting changes in Connect-CrmOnlineDiscovery for easier usage 
- centralized the connection verification
=> Add centralized connection verification

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Finalizing centralized connection validation function.
=> fixed more connection verification areas

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Adding first implementation of Connect specifically for CRM OnPrem and it will work nearly the same as online, with a focus on using a custom onprem discovery server. Longer term Ken & I are considering going to just two connections discovery and url specific but we need to do some additional work before we can consider that.
=> Added crmonprem discovery

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Added error handling for many functions, fixed error handling for Set-CrmRecordOwner
For CrmServiceClient methods which return Boolean, added following code
```powershell
if(!$result)
{
return $conn.LastCrmException
}
```
For other methods, added following.
```powershell
if($result -eq $null)
{
return $conn.LastCrmException
}
```
Also updated $conn.LastCrmError to $conn.LastCrmException as LastCrmError doesn't useful information time to time.
Fixed error handling logic for Set-CrmRecordOwner by following above rule.
I didn't touch any CrmSolution related functions as they are more complex.
=> Fix for issue #19

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
fix logic for Test-CrmViewPerformance
=> fix logic for Test-CrmViewPerformance

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Change parameterset name for Connect-CrmOnPremDiscovery
=> Change parameterset name for Connect-CrmOnPremDiscovery

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> update Connect-CrmOnPremDiscovery parametersetname

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> fixed Test-CrmViewPerformance

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Fixed Test-CrmViewPerformance to remove unnecessary data
=> Fixed Test-CrmViewPerformance to remove unnecessary data

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> issue-41 fixed

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> fixed issue 41

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Added check to see if the solution file exists prior to trying the import.
=> Fix for Issue 47

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
I added two new functions that mirror the functionality included in the SDK samples, ExportRibbonXml.cs.
=> Added Get-CrmEntityRibbonXml and Export-CrmEntityRibbonXml

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Export was failing due to "unexpected parameter 'ExportSales'"  This fixed the problem, but perhaps it might be better to check -gt 6?
=> Added fixed for CRM 2013 Export

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
fixed issue 62
Explicitly returned crafted error before but simply returns $conn.LastCrmException now
=> Fixed issue 62

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> fixed issue-60

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Added -Verbose for all Get-CrmConnection
=> Added -Verbose for all Get-CrmConnection

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> fixed issue 70

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Recreating #119 to target Import-Solution branch
=> Fix false positive on solution import if there are missing dependencies

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
add $null value check for set-crmrecord
=> add $null value check for set-crmrecord

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Introduces the new function "Get-FieldTypeByFieldValue". This function
is responsible to map the value of a field to the corresponding CRM-Data-Type.
=> Fix for issue #153

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
New functions have been added to grant, modify, and revoke access to CRM records to address issue #151.
Granting is performed using Grant-CrmRecordAccess. It encapsulates the CRM SDK's [GrantAccessRequest](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.grantaccessrequest.aspx).
Modifying is performed using Set-CrmRecordAccess. It encapsulates the CRM SDK's [ModifyAccessRequest](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.revokeaccessrequest.aspx)
Revoking is performed using Revoke-CrmRecordAccess. It encapsulates the CRM SDK's [RevokeAccessRequest](https://msdn.microsoft.com/en-us/library/microsoft.crm.sdk.messages.revokeaccessrequest.aspx).
=> New cmdlets for Grant-CrmRecordAccess, Revoke-CrmRecordAccess, and Set-CrmRecordAccess

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.Help.pshproj, Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.Help.xml, Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> added Publish-CrmTheme

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> fixed issue 144

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
We no longer need support for LiveId/CTP auth
=> Removed UseCtp for bug #196

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Added check for null response and re-throw the underlying error message.
=> Export solution timeout fix

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Changing write-information over to write-verbose to accommodate PS4 Backwards Compat as in bug #199
=> Switching from write-info to Write-Verbose

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Instead of a break we should throw an error.
=> Fix verify connection break

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.Help.pshproj, Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.Help.xml
#216 Added a link to a list of valid version numbers.
=> Added examples of valid version numbers.

BuildAndDeploy/appveyor.yml, CONTRIBUTE.md, README.md
Updated readme content and build scripts for new build automation
=> Build Updates

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Letting the platform handle any necessary validation
=> Remove Email address validation as it was too restrictive

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Try to throw the exception with the most information and the first non null exception.  Centralized the "finding" of the exception to help make things easier to adjust in the future
=> Add a single function to attempt throwing a relevant non-null exception

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> Set crm user mailbox parameter bug

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
function AddTls12Support was added and will remain until the Xrm connector can handle this itself in powershell
=> Add TLS 1.2 support by default and drop SSL3 support

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psd1, Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> Timeout fix

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> Updated validation pattern

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
https://regex101.com/r/sweY5Z/1/
Updating pattern to match for: 
https://test.crm.dynamics.com 
https://test.crm1.dynamics.com 
https://test.crm2.dynamics.com 
https://test.crm3.dynamics.com 
https://test.crm4.dynamics.com 
https://test.crm5.dynamics.com 
https://test.crm6.dynamics.com 
https://test.crm7.dynamics.com 
https://test.crm8.dynamics.com 
https://test.crm9.dynamics.com 
https://test.crm10.dynamics.com 
https://test.crm11.dynamics.com 
https://test.crm.dynamics.de
https://test.crm.microsoftdynamics.de
=> Updating pattern

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.Help.xml, Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
-UseAllowUsersSeeAppdownloadMessage
-DefaultCrmCustomName
-SuppressSLA
-IsAuditEnabled
=> Added the below settings for Set-CrmSystemSettings:

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Added verbose trace to connect-crmonline connection string (minus the pw) for easier debugging of connections.
=> Added verbose trace to connect-crmonline

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> Added parameter for isenabledforallroles

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psd1, Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
added new timeout setting 
updated manifest for 2.8.6 
Edited year to 2020
=> added new timeout setting and updated manifest

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
- Added Merge-HoldingSolution function
- Fixed log issues in Import-CrmSolutionAsync function
- Resolved other minor log issues to improve code readability
=> [Issue #406] Delete and Promote request (Apply holding solution upgrade)

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> Applying workflow fixes

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psd1, Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Fixing bug in #428 identified by user in #432
=> Fixing bug #428

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
Resolves issue from #456 using PR #255 as guidance.
=> Remove Email address validation in alignment with pr #255

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psd1
Fixed a bug in the parameter set for Add-CrmSecurityRoleToUser
=> Fixed a bug in the parameter set for Add-CrmSecurityRoleToUser

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> Adding missing connection parameters on some internal calls

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psm1
=> Refactor recursive Get-CrmRecordsByFetch into a loop to prevent stack overflow when a large number of records are fetched

Microsoft.Xrm.Data.PowerShell/Microsoft.Xrm.Data.PowerShell.psd1
updating release notes for .16 in the gallery
=> Updating release notes for .16 release
